version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: monthly
    groups:
      microsoft-extensions:
        patterns:
          - microsoft.extensions.*
      xunit:
        patterns:
          - xunit*

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

