name: Build alpha package

on:
  workflow_dispatch:


jobs:
  build:
    name: Build Alpha Package
    runs-on: ubuntu-latest
    timeout-minutes: 10

    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      PACKAGE_PATH: artifacts

    steps:
      - name: Clone repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Create NuGet package
        run: >
          dotnet pack
          --configuration Release
          --no-build
          --no-restore
          --output ${{ env.PACKAGE_PATH }}
          --version-suffix alpha-build$GITHUB_RUN_NUMBER
          -property:RepositoryCommit=$GITHUB_SHA

      - name: Push to NuGet
        run: >
          dotnet nuget
          push ${{ env.PACKAGE_PATH }}/*
          --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json

